### ISSUE TITLE
Title from another page after the script checks for new notifications

### ISSUE THREAD

**Issue by gizellos** [revilheart/GitHub-Notifier#1]
I am not sure if it is a bug of the script but I believe so. When I go to a page on github, I can see the right title text in the tab but after a while the text will change to a title of an issue page. I suspect that the script changes it after it checks if there are some new notifications. It seems to be the title of the page I visited before the current one.

![2017-08-06_220305](https://user-images.githubusercontent.com/2397851/29006591-3cd4c0cc-7af3-11e7-8030-49a8068c061f.png)

**Comment by gizellos** [comment]
Sorry, but I have to bump this issue. Please check it, it is quite annoying.

**Comment by revilheart** [comment]
Fixed
